[build]
  publish = "."

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/services.html"
  to = "/services"
  status = 301
  force = true

[[redirects]]
  from = "/featured.html"
  to = "/featured"
  status = 301
  force = true

[[redirects]]
  from = "/gallery.html"
  to = "/gallery"
  status = 301
  force = true

[[redirects]]
  from = "/faq.html"
  to = "/faq"
  status = 301
  force = true

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/terms-conditions.html"
  to = "/terms-conditions"
  status = 301
  force = true

[[redirects]]
  from = "/product.html"
  to = "/product"
  status = 301
  force = true

[[redirects]]
  from = "/journals.html"
  to = "/journals"
  status = 301
  force = true

[[redirects]]
  from = "/journal.html"
  to = "/journal"
  status = 301
  force = true

[[redirects]]
  from = "/wishlist.html"
  to = "/wishlist"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/featured"
  to = "/featured.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-conditions"
  to = "/terms-conditions.html"
  status = 200

[[redirects]]
  from = "/product"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/journals"
  to = "/journals.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/journal.html"
  status = 200

[[redirects]]
  from = "/wishlist"
  to = "/wishlist.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true
